### ISSUE TITLE
Failed to install addon: `apk add --no-cache 'rsync' 'coreutils' 'curl'' returned a non-zero code: 2`

### ISSUE THREAD

**Issue by FloThinksPi** [googanhiem/gords-ha-addons#1]
Hey @googanhiem,

i wanted to try this addon however i get a strange error when trying to install it via the supervisor addon store on a RPI4:

`The command '/bin/ash -o pipefail -c apk update && apk add --no-cache 'rsync' 'coreutils' 'curl'' returned a non-zero code: 2`

Have you seen this before ? I installed the plugin two other machines however the other instances runson x86 and there it worked.
Maybe related to the architecture ?

**Comment by googanhiem** [comment]
Hmmm, I haven't seen this. It's essentially saying that it cannot find these packages, which is weird as they're really common utilities. Have you experienced any network issues with this system?

Might be an issue with using the oldest (soon to be deprecated) image of HA official Alpine docker image. I've updated it from the oldest to newest image.  YOLO... I don't usually update this stuff as it breaks everything, but looks fine so far. 

I don't have a rpi4 to test this on (switched to running hass as a VM on my NAS back when pi's were unobtainium - I don't even use this addon anymore 😞 as I just snapshot my vm) . Give it a try and report back.

**Comment by FloThinksPi** [comment]
Yea likely network it seems :) 

```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/aarch64/APKINDEX.tar.gz

fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/aarch64/APKINDEX.tar.gz

WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.19/main: temporary error (try again later)

WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.19/community: temporary error (try again later)
```
